### ISSUE TITLE
Class 'Nord\Lumen\Elasticsearch\ElasticsearchServiceProvider::class' not found 

### ISSUE THREAD

**Issue by S43534** [nordsoftware/lumen-elasticsearch#6]
Directly after a clean installation of Lumen and lumen-elastic-search I get: 
Fatal error: Class 'Nord\Lumen\Elasticsearch\ElasticsearchServiceProvider::class' not found in /home/vagrant/Code/imp-api/vendor/laravel/lumen-framework/src/Application.php on line 162

Lumen 5.2.6, lumen-elasticsearch dev-master/0.2.0

Can't imagine what I could have done wrong?!

Thanks,
Sebastian

**Comment by crisu83** [comment]
Could you check your PSR-4 autoloader (in vendor/composer) that Composer has mapped the module correctly for autoloading. If not, you can try running `composer dumpautoload` to rebuild the autoloader.

**Comment by crisu83** [comment]
Oh I found the issue, remove the quotes from the `register` call and it should work fine. I fixed this in the readme just now.

**Comment by S43534** [comment]
Thanks. Unbelievable that I didn't see this myself.

**Comment by crisu83** [comment]
No problem.
